AllCops:
  NewCops: disable
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
  Exclude:
    - 'app/tests.rb'
    - 'app/repl.rb'

# Incompatible with x, y, etc
Naming/MethodParameterName:
  Enabled: false

# This will complain about :my_image_1 used in SpriteRegistry
# I don't really want to enforce a style here.
Naming/VariableNumber:
  Enabled: false

# Doesn't seem to be a clean way to skip enforcing this for abstract classes
Lint/MissingSuper:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

# A lot of this shit is blown up by assigning x/y/w/h/path/source_x/source_y etc all the damn time
Metrics/AbcSize:
  Max: 100

Metrics/BlockLength:
  Max: 100

Metrics/ClassLength:
  Max: 1000

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/MethodLength:
  Max: 100

Metrics/PerceivedComplexity:
  Max: 10

Style/AccessorGrouping:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/IfInsideElse:
  AllowIfModifier: true

Style/RandomWithOffset:
  Enabled: false

Style/RedundantFileExtensionInRequire:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

# Normally I like using double quotes but I think DR/mRuby can't hang
Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedColonStyle: table

# Ignoring comment lines due to YARD
Layout/LineLength:
  Max: 120
  AllowedPatterns: ['^ *# ']

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
